### PR TITLE
Clarify that we are recommending Ed25519

### PR DESCRIPTION
**Pull request by joshuagl**
First attempt at addressing #21 by making it clear we are recommending Ed25519 for PyPI

### CODE REVIEW

**Review by lukpueh — APPROVED** [review]
LGTM!

**Comment by trishankatdatadog** [comment]
@joshuagl pls fix conflict, thx

**Review by trishankatdatadog — CHANGES_REQUESTED** [review]
LGTM, but please fix conflicts? Thanks!

**Comment by joshuagl** [comment]
Conflicts fixed in a force push.

**Review by trishankatdatadog — APPROVED** [review]

**Pull request merged**
