### PR TITLE
Transition plan

### PR DESCRIPTION
**Pull request by JustinCappos**

### CODE REVIEW

**Review by trishankatdatadog — CHANGES_REQUESTED** [review]
Comments:

1. We already discuss pip disabling TUF when necessary elsewhere (see "--no-pep-458").
2. It doesn't describe a concrete plan for pip and PyPI to work together on gradually enabling this.
3. It doesn't describe how to collect bug reports for when things go wrong.
4. It doesn't explain what to do when a large number of users are experiencing a PEP-458-related issue.

**Comment by JustinCappos** [comment]
Okay, then my commit seems pretty useless and likely should be discarded.  I'm not sure how to  address point 3 or 4 you made.  As for 2, I would just say that Warehouse generates the metadata first then pip rolls out the check.  I'm not sure what else to say.

**Comment by trishankatdatadog** [comment]
Maybe we should have a meeting to discuss this? Because I don't think this is an issue to be taken lightly. We can fix this by the 31st, if not tomorrow.

**Comment by JustinCappos** [comment]
Fine by me.  Let's schedule on slack.

**Comment by trishankatdatadog** [comment]
We are planning to discuss this with Ernest and Donald

**Comment by lukpueh** [comment]
The corresponding issue #47 was closed based on conversation on [Python Discourse](https://discuss.python.org/t/pep-458-secure-pypi-downloads-with-package-signing/2648/57), which deemed a transition plan as out of scope for this PEP. Closing here too...

**Pull request closed without merging**
