### PR TITLE
Update PEP 480 to account for changes to PEP 458

### PR DESCRIPTION
**Pull request by mnm678**
This commit adds various update to account for changes in PEP 458, including:
* updating the link to the Python glossary
* add definitions of distribution file, target files
* clarify ‘target files’ and ‘target metadata’
* Use BLAKE 2 instead of SHA-2 in filenames
* transaction process -> upload process

This commit also adds a few clarifications about the purpose of this PEP, including adding an overview of the changes needed to implement the PEP

### CODE REVIEW

**Review by trishankatdatadog — APPROVED** [review]

**Comment by trishankatdatadog** [comment]
Wunderbar, thanks! Could we update the PyPA master version going forward, please? Maybe we don't need this copy anymore...

**Comment by mnm678** [comment]
> Wunderbar, thanks! Could we update the PyPA master version going forward, please? Maybe we don't need this copy anymore...

Yes, I'll re-open this in the python/peps repo

**Comment by mnm678** [comment]
Reopened here: https://github.com/python/peps/pull/1681

**Comment by trishankatdatadog** [comment]
Thank you 🙏🏽 Maybe we should archive this repo, no?

**Pull request closed without merging**
